SHELL = /bin/bash
CC = gcc
CFLAGS = -std=c11 -pedantic -Werror -Wall -g3 -DNDEBUG

#CC=clang-3.5
#-Wno-variadic-macros 
#-DNDEBUG
#CFLAGS=-std=c11 -pedantic -ggdb3 -Werror -Wall -g3

all: ex20

ex20: dbg.h

clean:
	rm -f ex20