SHELL = /bin/bash
CC = gcc
CFLAGS = -std=c11 -pedantic  -Wall -g3 -DNDEBUG

##-Werror

#CC=clang-3.5
#-Wno-variadic-macros 
#-DNDEBUG
#CFLAGS=-std=c11 -pedantic -ggdb3 -Werror -Wall -g3

all: ex21
	./ex21

clean:
	rm -f ex21