PREFIX ?= /usr/local
CFLAGS = -Werror -std=c11 -pedantic -g3 -ggdb3  -Wall -Wextra -I${PREFIX}/apr/include/apr-1 -I${PREFIX}/apr/include/apr-util-1
LDFLAGS = -L${PREFIX}/apr/lib -lapr-1 -pthread -laprutil-1
#LDFLAGS= -L${PREFIX}/apr/lib -L .aprutil-1 -L .apr-1
LDLIBS=  -lapr-1 -laprutil-1
